### ISSUE TITLE
DownloadXPortraitModel: - Exception when validating inner node: 'required'

### ISSUE THREAD

**Issue by CavaronEV** [akatz-ai/ComfyUI-X-Portrait-Nodes#7]
Hi, any idea what that's supposed to mean (I'm a noob, but I installed all required custom nodes...):

Prompt outputs failed validation
DownloadXPortraitModel:
    - Exception when validating inner node: 'required'

![Error](https://github.com/user-attachments/assets/9fe74f26-e10d-4fa8-8c27-3ad3f8379348)

**Comment by akatz-ai** [comment]
Hmm I've never seen that before, can you please disable workflow validation (if enabled) and try again?

![Screenshot 2024-11-16 143839](https://github.com/user-attachments/assets/18388aab-45f4-43e1-b5d6-2eedffda136e)

If that doesn't work you may be on a different version of ComfyUI than me, I'm currently on release [v0.2.5](https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.2.5)

**Comment by CavaronEV** [comment]
Thanks for your fast reply. So I was on 0.2.7, couldn't find that option and switched to 0.2.5. This error does not appear any more, but instead: "No module named 'xformers'". Here are the logs:

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
Model loaded from: C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\x-portrait\model_state-415001.th
!!! Exception during processing !!! No module named 'xformers'
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 165, in _map_node_over_list
    process_inputs({})
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\nodes.py", line 82, in load_model
    model = create_model(self.model_config).cpu()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\model_lib\ControlNet\cldm\model.py", line 24, in create_model
    model = instantiate_from_config(config.model).cpu()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\model_lib\ControlNet\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\model_lib\ControlNet\ldm\util.py", line 87, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\model_lib\ControlNet\cldm\cldm.py", line 14, in <module>
    from model_lib.ControlNet.ldm.models.diffusion.ddpm import LatentDiffusionReferenceOnly
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\model_lib\ControlNet\ldm\models\diffusion\ddpm.py", line 26, in <module>
    from model_lib.ControlNet.ldm.models.autoencoder import IdentityFirstStage, AutoencoderKL
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\model_lib\ControlNet\ldm\models\autoencoder.py", line 6, in <module>
    from model_lib.ControlNet.ldm.modules.diffusionmodules.model import Encoder, Decoder
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\model_lib\ControlNet\ldm\modules\diffusionmodules\model.py", line 12, in <module>
    import xformers
ModuleNotFoundError: No module named 'xformers'

Prompt executed in 0.47 seconds

Like I said, I'm a total noob. I might still need to set something up that seems totaly basic to other users (though I managed to get the AdvancedLivePortrait custom node to work) . 
I get some weird python "this is not part of PATH" messages. But I don't know how to fix this. I did follow a tutorial how to set up ComfyUI and it told me to install Python 3.11 which I did. Maybe there are more steps required? There are messages like that:

  WARNING: The script pygmentize.exe is installed in 'C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.

C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

**Comment by akatz-ai** [comment]
Hi @CavaronEV, installing xformers on windows is a challenge due to needing to match the current cuda and pytorch versions I believe, so if there is no wheel found pip tries to compile xformers which requires build tools to be installed. I'm working on a comfyui environment manager that I hope to share soon that should help with environment related install issues.

**Comment by Eydahn8** [comment]
i'm having the same issues, i was having "missing xformers module", installed it, then "missing triton module" installed it, now this one, but i can't find where i can disable workflow validation, can you please point me out where i can find it?
