### ISSUE TITLE
Failed to find C compiler. Please specify via CC environment variable

### ISSUE THREAD

**Issue by sugatasanshiro** [akatz-ai/ComfyUI-X-Portrait-Nodes#9]
![brave_WtmoIuaBky](https://github.com/user-attachments/assets/2e3f4e13-a9c2-47d5-95e5-bf51cec7f197)

![cmd_Q5muz7UIcA](https://github.com/user-attachments/assets/60fc511d-16a0-4c93-aeb4-2d819302d8a6)

![cmd_lXfhMqlmuE](https://github.com/user-attachments/assets/8b139095-50b0-4a0b-b82d-32bff6c52c27)

![cmd_tYyCyrAFtQ](https://github.com/user-attachments/assets/f83d6051-5037-428d-b0eb-b21ad4407c48)

Best Frame: 5
!!! Exception during processing !!! Failed to find C compiler. Please specify via CC environment variable.
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\nodes.py", line 166, in generate
    output_video = xportrait_main(args, xportrait_model)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\core\test_xportrait.py", line 411, in main
    output_videos.append(visualize_mm(args, "inference", infer_batch_data, infer_model, nSample=nSample, local_image_dir=args.output_dir, num_mix=args.num_mix))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\core\test_xportrait.py", line 265, in visualize_mm
    pre_noise.append(infer_model.get_first_stage_encoding(infer_model.encode_first_stage(cond[i:i+vae_bs])))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\model_lib\ControlNet\ldm\models\diffusion\ddpm.py", line 2113, in encode_first_stage
    return self.first_stage_model.encode(x)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\model_lib\ControlNet\ldm\models\autoencoder.py", line 83, in encode
    h = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\model_lib\ControlNet\ldm\modules\diffusionmodules\model.py", line 602, in forward
    h = self.mid.attn_1(h)
        ^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-X-Portrait-Nodes\model_lib\ControlNet\ldm\modules\diffusionmodules\model.py", line 317, in forward
    out_seg = sageattn(q_seg, k_seg, v_seg, is_causal=is_causal, smooth_k=smooth_k)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sageattention\core.py", line 101, in sageattn
    q_int8, q_scale, k_int8, k_scale = per_block_int8(q, k, sm_scale=sm_scale, tensor_layout=tensor_layout)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sageattention\quant_per_block.py", line 63, in per_block_int8
    quant_per_block_int8_kernel[grid](
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 160, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 341, in run
    device = driver.get_current_device()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 22, in __getattr__
    self._initialize_obj()
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 19, in _initialize_obj
    self._obj = self._init_fn()
                ^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 8, in _create_driver
    return actives[0]()
           ^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 411, in __init__
    self.utils = CudaUtils()  # TODO: make static
                 ^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 55, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 32, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dir, include_dir, libraries)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\build.py", line 52, in _build
    raise RuntimeError("Failed to find C compiler. Please specify via CC environment variable.")
RuntimeError: Failed to find C compiler. Please specify via CC environment variable.

Prompt executed in 315.97 seconds

**Comment by slmonker** [comment]
same

**Comment by SvKora** [comment]
Rather, you need to install all the tools for triton, as indicated in the instructions. https://github.com/woct0rdho/triton-windows?tab=readme-ov-file

**Comment by Eydahn8** [comment]
> Rather, you need to install all the tools for triton, as indicated in the instructions. https://github.com/woct0rdho/triton-windows?tab=readme-ov-file

thanks for your reply, i finally made it work

**Comment by tutnyal** [comment]
I was also getting the same issue with Linux system. Is it the same solution?

> Rather, you need to install all the tools for triton, as indicated in the instructions. https://github.com/woct0rdho/triton-windows?tab=readme-ov-file
